name: Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@swarthiii'

      - name: NPM CI
        run: npm ci

      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: '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'
