name: Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@_swarthi_'

      - name: Install Dependencies
        run: yarn install

      - name: Publish to npm
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: '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'
